// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmprestimoLivros.DATA.Models
{
    public partial class SP_SelecionarTodosByClienteIDResult
    {
        public string cliCPF { get; set; }
        public string cliNome { get; set; }
        public string livroNome { get; set; }
        public int id { get; set; }
        public int LceIdCliente { get; set; }
        public int LceIdLivro { get; set; }
        public DateTime LceDataEmprestimo { get; set; }
        public DateTime LceDataEntrega { get; set; }
        public bool LceEntregue { get; set; }
    }
}
