// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EmprestimoLivros.DATA.Models
{
    public partial class VwLivroClienteEmprestimo
    {
        [Required]
        [Column("cliCPF")]
        [StringLength(14)]
        public string CliCpf { get; set; }
        [Required]
        [Column("cliNome")]
        [StringLength(200)]
        public string CliNome { get; set; }
        [Required]
        [Column("livroNome")]
        [StringLength(50)]
        public string LivroNome { get; set; }
        [Column("id")]
        public int Id { get; set; }
        public int LceIdCliente { get; set; }
        public int LceIdLivro { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LceDataEmprestimo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LceDataEntrega { get; set; }
        public bool LceEntregue { get; set; }
    }
}